### ISSUE TITLE
IntelliSenseX - by Dot clears an Editbox

### ISSUE THREAD

**Issue by lscheffler** [VFPX/IntelliSenseX#26] opened 2023-12-11 09:11 UTC
## 📝 Provide detailed reproduction steps (if any)

I have a form I use to create PEM with an editbox for comment. As soon as  I enter a dot ".", all text is cleared and only the dot remains.

I tried a fresh install starting with fresh Thor, the behaviour is not changing. Without IntelliSenseX - by Dot, the input works as expected.

The editbox is not of Class *Editbox*, but of BaseClass *Editbox*.

The code could be provided on request.

**Comment by Jimrnelson** [comment] 2023-12-19 21:27
This problem was recognized very early on in the development of IntellisenseX by dot.

The issue is that IntellisenseX by dot uses On Key Label . which works as designed when in a code window but fails in other windows (textboxes, editboxes, the debugger, etc.)

The solution is to use a timer that ensures that On Key Label is only set when in an code window. 

This solution is enabled here:

![image](https://github.com/VFPX/IntelliSenseX/assets/81179335/d9376df3-edeb-495f-9e2d-7fa0bdf1c6a5)

The default setting is off, as some users did not like having this timer constantly firing.

**Comment by lscheffler** [comment] 2023-12-20 05:15
I dislike this timer either. Just checking the target to be a VFP object was no option?

**Comment by Jimrnelson** [comment] 2023-12-20 23:23
The code to achieve IntellisenseX starts essentially like this:
 
    On Key Label . HandleDot()

So HandleDot.PRG takes over processing whenever the user presses a dot.  

All is fine if the focus is a code window.

However, when the focus is not a code window, there is no way for it to 'get out of the way' so that normal processing of the dot can continue.  Once HandleDot is called, it's too late for it to say "Oops, did not mean to process that dot -- VFP you handle it."

Thus, to be able to handle a dot normally in a non-code window, the On Key Label must be turned off.  You can use the timer, if that works for you; if not, you must disable (and later re-enable) manually.

**Comment by lscheffler** [comment] 2023-12-21 09:05
Hi Jim,

I'm just curious. I understand that to proc is called as soon as the key is pressed.   
Is there no way using _SCREEN.ACTIVEFORM or the API calls to figure out what object is active, *inside HandleDot*, and if not on a prg / method / command window just do nothing?

Update:   
What real odd is, the **whole text** left of the dot is deleted, not just a word or a char, even over white space boundaries. While there is an odd syntax to have a white space around a dot in an object, a white space without a dot is a boundary in any case. I enter a sentence for a comment, add a point, and the whole sentence is deleted.

**Comment by Jimrnelson** [comment] 2023-12-21 19:40
Hey Lutz --

Now you have my curiosity as well.  My first instinct was to say that ISX already does nothing when not in a code window.  

Clearly, though, that is not the case, it certainly does _something_ (as you noted it does odd things in an editbox and presumably other non-code windows.)

IntellisenseX was adapted from `ISX.PRG` by Christof and much of his original code remains intact.  It might very well be that the code for "not in a code window" has never been changed (or maybe even be read).

I'll be happy to investigate this when time permits.

**Comment by lscheffler** [comment] 2023-12-21 19:47
Hey Jim,    
Possibly I will have a look myself - when time permits, or if I need to procrastinate something else.

**Comment by lscheffler** [comment] 2023-12-22 20:41
@Jimrnelson 

####  Test
I've done a simple test
In Thor_Proc_ISX.prg I changed
```
* Main program
*========================================================================================
Lparameters tcProviders, tcInvocation, tlForceThor, TOList, tlSearchSecondColumn, toPostProcessor, tlReturnResult, tcEntity

Local loISX, loResult

Push Key Clear
```
to
```
* Main program
*========================================================================================
Lparameters tcProviders, tcInvocation, tlForceThor, TOList, tlSearchSecondColumn, toPostProcessor, tlReturnResult, tcEntity

Local loISX, loResult

?TYPE("_screen.ActiveForm")
Push Key Clear
```
And then I run this against some places to input a dot 
| Source | Return | Deletes text left of dot |
| -- | -- | -- |
| Command Window | U | N |
| Method Window | U | N |
| Modi Comm | U | N |
| Modi File (sic!) | U | N |
| Build in dialogue (Edit property or New Method) | nothing | N |
| Properties Window | U | N |
| EditBox on _SCREEN | nothing | N |
| EditBox on my VFP form with the problem | O | Y |
| EditBox on VFP form. (numb scx with just an EditBox) | O | N |

So, somehow my Form is different.  

#### Closer Test  

The culprit is `SelectOnEntry`  As soon as it is .T., it deals `ON KEY LABEL` like loosing and getting focus.

To test:
1. Run plain VFP without Thor and IntellisenseX
2. Create a From with an Editbox, set `Editbox.SelectOnEntry = .t.`
3. On command window `ON KEY Label . Keyboard "." Plain Clear && return a dot if a dot is pressed`
4. Run the form
5. enter some chars, then a dot

Result: All input except the dot is gone

Retry with `Editbox.SelectOnEntry = .f.`, and with `ON KEY LABEL .`

Thor / IntellisenseX has no influence here.  As soon as `SelectOnEntry` is .T., it deals `ON KEY LABEL` like loosing and getting focus, marking all and then replace with the dot.

####  Solution
So, we know when and what, why not use this? We replace the snippet from above like
```
* Main program
*========================================================================================
Lparameters tcProviders, tcInvocation, tlForceThor, TOList, tlSearchSecondColumn, toPostProcessor, tlReturnResult, tcEntity

LOCAL loISX, loResult

*SF 20231222, Fix the problem with dot clearing input https://github.com/VFPX/IntelliSenseX/issues/26
IF TYPE("_screen.ActiveForm")='O' AND TYPE("_screen.ActiveForm.Activecontrol")='O';
  AND PEMSTATUS(_SCREEN.ACTIVEFORM.ACTIVECONTROL,"SelectOnEntry",5) AND _SCREEN.ACTIVEFORM.ACTIVECONTROL.SELECTONENTRY THEN

 _SCREEN.ACTIVEFORM.ACTIVECONTROL.VALUE = STUFF(;
  _SCREEN.ACTIVEFORM.ACTIVECONTROL.VALUE,;
  _SCREEN.ACTIVEFORM.ACTIVECONTROL.SELSTART+1,;
  _SCREEN.ACTIVEFORM.ACTIVECONTROL.SELLENGTH,;
  m.tcInvocation)

 RETURN
ENDIF &&TYPE("_screen.ActiveForm")='O' AND TYPE("_screen.ActiveForm.Activecontrol")='O' AND PEMSTATUS(_screen. ...
*/SF 20231222, Fix the problem with dot clearing input https://github.com/VFPX/IntelliSenseX/issues/26

PUSH KEY CLEAR
```

IOW we force the dot (or any input, for that) into the object via it's value. We can advance it by checking for READONLY, if we like.

**Comment by lscheffler** [comment] 2023-12-22 20:49
@Jimrnelson, @DougHennig I will create a pull request the next days, it's easy enough. Should I include VFPXDeployment?

**Comment by Jimrnelson** [comment] 2023-12-22 20:56
No, please do not -- at least not yet.

I have a solution as well that I am just about to release using VFPX Deployment -- I was about 5 minutes away from committing this new version when your email arrived.

I have taken a different approach which, I hope will be a satisfactory solution.

**Comment by lscheffler** [comment] 2023-12-22 21:04
@Jimrnelson Sure, I wait. That's this *... the next days ....* It's 2hours to midnight, I had enough fun for this day. Just make sure to only solve it for the problem I point you to. I tried for a while, and nothing then changing `VALUE` solved it. But it's only valuable in this special case, anything else runs.

**Comment by Jimrnelson** [comment] 2023-12-22 23:36
Attempted fix in Version 1.25, 2023-12-22.

This problem has to do with how IntellisenseX responds when a dot is pressed when the focus in not in an edit window (such as a form, debugger, property window, etc.)

Until now the solution is to have a timer which disables `On Key Label .` when not in an edit window, a solution that is not optimal.

It is my belief that this solution does work correctly when the timer is turned off.  Unfortunately, it's not possible to find all possible circumstances, so this, too, may be an imperfect solution.

Note that the timer is enabled/disabled here:

![image](https://github.com/VFPX/IntelliSenseX/assets/81179335/89741cf2-0055-401d-b1de-2c5a70e609d2)

**Comment by lscheffler** [comment] 2023-12-23 16:07
<s>@Jimrnelson I'm beg your pardon. Do you read my [message](https://github.com/VFPX/IntelliSenseX/issues/26#issuecomment-1868055677) above?

This problem **only becomes visible** with IntelliSenseX. One don't need IntelliSenseX to raise it.

The problem is native to `Keyboard "." Plain Clear` when an EditBox (not tested with TextBox, ComboBox ... ) has the focus, and if the Editboxes *SelectOnEntry* property is set to is .T. . New VFP bug.

The code provided in the message solves the problem for anything that owns *SelectOnEntry* property - and I can not raise this problem otherwise.

----
The timer is a kludge, and I guess it will not survive the next `Clear All` anyway.</s>

Works, could be closed. Thanks

**Comment by Jimrnelson** [comment] 2024-01-01 16:39
> Works, could be closed. Thanks

Glad this has been resolved.  I am closing this issue.

**Closed as completed by Jimrnelson** 2024-01-01 16:39 UTC
Labels: bug, enhancement
